version: "3.8"

services:
  app:
    container_name: innoscripta-assignment
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]
    env_file:
      - .env.development.local
